name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build binary
        run: deno compile --allow-read --allow-write --allow-env --output bkv src/main.ts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bkv-${{ matrix.os }}
          path: bkv